steps:
# Decrypt the file containing the key and place the decrypted file 'ssh' volume
- name: 'gcr.io/cloud-builders/gcloud'
  #id: 'decrypt'
  args:
  - kms
  - decrypt
  - --ciphertext-file=fabmKey.enc
  - --plaintext-file=/root/.ssh/fabmKey
  - --location=global
  - --keyring=jlg-keyring
  - --key=gitlab-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh
      

# Set up git access with decrypted key
- name: 'gcr.io/cloud-builders/git'
  #waitFor: 'decrypt'
  id: 'setKey'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/fabmKey
    cat <<EOF >/root/.ssh/config
    Hostname gitlab.au.dk
    IdentityFile /root/.ssh/fabmKey
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# cloning fabm: requires key
- name: 'gcr.io/cloud-builders/git'
  #id: 'cloneFABM'
  waitFor: ['setKey']
  args:
  - clone
  - git@gitlab.au.dk:anbios/fabm-prognos.git
  - /root/gotm/fabm-prognos
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'gotm'
    path: /root/gotm/
    
#cloning gotm
- name: 'gcr.io/cloud-builders/git'
  #id: 'cloneGOTM'
  args: 
  - clone
  - -b
  - lake
  - https://github.com/gotm-model/code.git
  - /root/gotm/code/
  waitFor: ['-']
  volumes:
  - name: 'gotm'
    path: /root/gotm

#Creating a debian docker image with the build environment
- name: 'gcr.io/cloud-builders/docker'
  #waitFor: ['-']
  #id: 'gotmBuilder'
  args: ['build', '-f', 'Dockerfile.gotm-build-tools', '-t', 'gotm-build', '.']
  volumes:
  - name: 'gotm'
    path: '/root/gotm'
  
#Actually creating the build environment using a bash script 
- name: 'gotm-build'
  args: ['bash', './gotm-fabm.sh']
  #waitFor: ['gotmBuilder', 'cloneGOTM', 'cloneFABM']
  #id: 'build'
  volumes:
  - name: 'gotm'
    path: '/root/gotm'

#Building docker image containing  gotm
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/nivacatchment/titio:latest', '.' ]
  #waitFor: 'build'
  volumes:
  - name: 'gotm'
    path: '/root/gotm'
  #entrypoint: '/root/gotm'

images:
#- 'gcr.io/nivacatchment/titio:latest'
- 'gcr.io/nivacatchment/gotm-build'
